# Generated by Django 4.2 on 2025-07-29 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('final', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.IntegerField(default=0, verbose_name='最低在庫数'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='定価'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='在庫数'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='個', max_length=10, verbose_name='単位'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='movement_type',
            field=models.CharField(choices=[('in', '入庫'), ('out', '出庫')], max_length=3, verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='operated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='担当者'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='quantity',
            field=models.IntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='日時'),
        ),
    ]
